# Generated by Django 5.0.6 on 2024-06-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
