# Generated by Django 5.0.4 on 2024-05-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('prix', models.FloatField()),
                ('quantite', models.IntegerField()),
                ('taille', models.IntegerField()),
                ('note', models.FloatField()),
                ('lit', models.IntegerField()),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('remise', models.IntegerField()),
                ('amenities', models.ManyToManyField(to='rooms.amenity')),
            ],
        ),
    ]
