# Generated by Django 5.0.4 on 2024-05-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('video', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/')),
                ('localisation', models.CharField(max_length=100)),
            ],
        ),
    ]
